version: '3.8'

services:
  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "5000:80" 
    environment:
      - REDIS_HOST=redis  
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  blazor:
    build:
      context: ./blazor
      dockerfile: Dockerfile
    ports:
      - "5124:80" 
    depends_on:
      - vote 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
