version: '3.8'

services:
  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Exponer Flask en el puerto 5000
    environment:
      - REDIS_HOST=redis  # La IP o nombre del servicio de Redis
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  blazor:
    build:
      context: ./blazor
      dockerfile: Dockerfile
    ports:
      - "5124:80"  # Exponer Blazor en el puerto 5124
    depends_on:
      - vote  # Asegurarse de que Flask esté disponible antes de iniciar Blazor
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
